// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: statistics_statistics.proto

package statistics

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetAmountOfProfitRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAmountOfProfitRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAmountOfProfitRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAmountOfProfitRequestMultiError, or nil if none found.
func (m *GetAmountOfProfitRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAmountOfProfitRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStartDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAmountOfProfitRequestValidationError{
					field:  "StartDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAmountOfProfitRequestValidationError{
					field:  "StartDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAmountOfProfitRequestValidationError{
				field:  "StartDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAmountOfProfitRequestValidationError{
					field:  "EndDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAmountOfProfitRequestValidationError{
					field:  "EndDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAmountOfProfitRequestValidationError{
				field:  "EndDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAmountOfProfitRequestMultiError(errors)
	}

	return nil
}

// GetAmountOfProfitRequestMultiError is an error wrapping multiple validation
// errors returned by GetAmountOfProfitRequest.ValidateAll() if the designated
// constraints aren't met.
type GetAmountOfProfitRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAmountOfProfitRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAmountOfProfitRequestMultiError) AllErrors() []error { return m }

// GetAmountOfProfitRequestValidationError is the validation error returned by
// GetAmountOfProfitRequest.Validate if the designated constraints aren't met.
type GetAmountOfProfitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAmountOfProfitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAmountOfProfitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAmountOfProfitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAmountOfProfitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAmountOfProfitRequestValidationError) ErrorName() string {
	return "GetAmountOfProfitRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetAmountOfProfitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAmountOfProfitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAmountOfProfitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAmountOfProfitRequestValidationError{}

// Validate checks the field values on GetAmountOfProfitResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAmountOfProfitResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAmountOfProfitResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAmountOfProfitResponseMultiError, or nil if none found.
func (m *GetAmountOfProfitResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAmountOfProfitResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Profit

	if len(errors) > 0 {
		return GetAmountOfProfitResponseMultiError(errors)
	}

	return nil
}

// GetAmountOfProfitResponseMultiError is an error wrapping multiple validation
// errors returned by GetAmountOfProfitResponse.ValidateAll() if the
// designated constraints aren't met.
type GetAmountOfProfitResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAmountOfProfitResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAmountOfProfitResponseMultiError) AllErrors() []error { return m }

// GetAmountOfProfitResponseValidationError is the validation error returned by
// GetAmountOfProfitResponse.Validate if the designated constraints aren't met.
type GetAmountOfProfitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAmountOfProfitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAmountOfProfitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAmountOfProfitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAmountOfProfitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAmountOfProfitResponseValidationError) ErrorName() string {
	return "GetAmountOfProfitResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetAmountOfProfitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAmountOfProfitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAmountOfProfitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAmountOfProfitResponseValidationError{}

// Validate checks the field values on TopProductsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TopProductsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TopProductsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TopProductsRequestMultiError, or nil if none found.
func (m *TopProductsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TopProductsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStartDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TopProductsRequestValidationError{
					field:  "StartDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TopProductsRequestValidationError{
					field:  "StartDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopProductsRequestValidationError{
				field:  "StartDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndDate()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TopProductsRequestValidationError{
					field:  "EndDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TopProductsRequestValidationError{
					field:  "EndDate",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndDate()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TopProductsRequestValidationError{
				field:  "EndDate",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.ProductType != nil {
		// no validation rules for ProductType
	}

	if len(errors) > 0 {
		return TopProductsRequestMultiError(errors)
	}

	return nil
}

// TopProductsRequestMultiError is an error wrapping multiple validation errors
// returned by TopProductsRequest.ValidateAll() if the designated constraints
// aren't met.
type TopProductsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TopProductsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TopProductsRequestMultiError) AllErrors() []error { return m }

// TopProductsRequestValidationError is the validation error returned by
// TopProductsRequest.Validate if the designated constraints aren't met.
type TopProductsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopProductsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopProductsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopProductsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopProductsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopProductsRequestValidationError) ErrorName() string {
	return "TopProductsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TopProductsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopProductsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopProductsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopProductsRequestValidationError{}

// Validate checks the field values on TopProductsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TopProductsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TopProductsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TopProductsResponseMultiError, or nil if none found.
func (m *TopProductsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TopProductsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResult() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TopProductsResponseValidationError{
						field:  fmt.Sprintf("Result[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TopProductsResponseValidationError{
						field:  fmt.Sprintf("Result[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TopProductsResponseValidationError{
					field:  fmt.Sprintf("Result[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TopProductsResponseMultiError(errors)
	}

	return nil
}

// TopProductsResponseMultiError is an error wrapping multiple validation
// errors returned by TopProductsResponse.ValidateAll() if the designated
// constraints aren't met.
type TopProductsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TopProductsResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TopProductsResponseMultiError) AllErrors() []error { return m }

// TopProductsResponseValidationError is the validation error returned by
// TopProductsResponse.Validate if the designated constraints aren't met.
type TopProductsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TopProductsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TopProductsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TopProductsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TopProductsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TopProductsResponseValidationError) ErrorName() string {
	return "TopProductsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TopProductsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTopProductsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TopProductsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TopProductsResponseValidationError{}

// Validate checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Product) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Product with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ProductMultiError, or nil if none found.
func (m *Product) ValidateAll() error {
	return m.validate(true)
}

func (m *Product) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	// no validation rules for Name

	// no validation rules for Count

	// no validation rules for ProductType

	if len(errors) > 0 {
		return ProductMultiError(errors)
	}

	return nil
}

// ProductMultiError is an error wrapping multiple validation errors returned
// by Product.ValidateAll() if the designated constraints aren't met.
type ProductMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProductMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProductMultiError) AllErrors() []error { return m }

// ProductValidationError is the validation error returned by Product.Validate
// if the designated constraints aren't met.
type ProductValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProductValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProductValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProductValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProductValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProductValidationError) ErrorName() string { return "ProductValidationError" }

// Error satisfies the builtin error interface
func (e ProductValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProduct.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProductValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProductValidationError{}
